### ISSUE TITLE
Parallelogram Boxes

### ISSUE THREAD

**Issue by tenten8401** [Addy771/Hex-Cell-Holder#10]
Any chance we could get boxes for parallelogram type batteries? Would be super useful for ebikes

**Comment by AlbertPhan** [comment]
This has been added with #11.

**Comment by tenten8401** [comment]
Awesome :)

**Comment by tenten8401** [comment]
@AlbertPhan you got a link I could donate a couple bucks to?

**Comment by AlbertPhan** [comment]
I have added a donation link to the end of the readme. Thanks!
