### ISSUE TITLE
Adjustable parallelogram angles

### ISSUE THREAD

**Issue by tenten8401** [Addy771/Hex-Cell-Holder#12]
Any chance we could get an adjustable angle for the parallelograms? It would obsolete the "rect" shape as you could just run a 90 deg angle. It would be useful for packs that need to be more pointy on one end or more rect-like

**Comment by AlbertPhan** [comment]
This would be a lot harder to do. I'm not sure how I would even implement this as the angle is set normally by the hexes. Ideally the perfect hex cell holder would be one where you could just give it a polygon and it would fit holders to that. If I have time again I could revisit it.

**Comment by tenten8401** [comment]
Hmm I see. Don't worry about it too much, I'm still very grateful for the work you've done already.
