### ISSUE TITLE
Cell removal obstructed

### ISSUE THREAD

**Issue by Addy771** [Addy771/Hex-Cell-Holder#8]
The current cell holder design has 3 tabs over each cell, which can be snapped off if a cell needs to be removed.

This won't work if a bus strip/wire passes over the cells. The bus will have to be removed first to make room for a cell to slide out.

One possible solution to this issue is to add extra space between cells, where the bus will be.

**Comment by Addy771** [comment]
This image shows the problem. For wider bus conductors like strips this is more of a concern.

![2019-05-25](https://user-images.githubusercontent.com/11689983/58375363-c056f880-7f05-11e9-831f-405718cc5194.jpg)

**Comment by AlbertPhan** [comment]
What we can do is when the bus style is chosen, we can have the cells automatically spaced apart based on the bus width distance to make sure the cells aren't obstructed. I will implement this when I have free time.

**Comment by AlbertPhan** [comment]
This feature was never really used so I am closing this issue.
